import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import Header from "@/components/header";
import SmoothScrolling from "@/components/smooth-scrolling";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body>
        <SmoothScrolling>
          <div className="w-full">
            <Header></Header>

            {children}
          </div>
        </SmoothScrolling>
      </body>
    </html>
  );
}
